export const EMOJI_MAP: Record<string, string> = {
  ':comet:': '☄️',
  ':rocket:': '🚀',
  ':star:': '⭐',
  ':fire:': '🔥',
  ':check:': '✅',
  ':x:': '❌',
  ':warning:': '⚠️',
  ':bulb:': '💡',
  ':memo:': '📝',
  ':calendar:': '📅',
  ':clock:': '🕐',
  ':hourglass:': '⏳',
  ':chart:': '📊',
  ':target:': '🎯',
  ':sparkles:': '✨',
  ':zap:': '⚡',
  ':heart:': '❤️',
  ':thumbsup:': '👍',
  ':thumbsdown:': '👎',
  ':question:': '❓',
  ':exclamation:': '❗',
  ':bell:': '🔔',
  ':pin:': '📌',
  ':link:': '🔗',
  ':folder:': '📁',
  ':file:': '📄',
  ':email:': '📧',
  ':phone:': '📞',
  ':globe:': '🌐',
  ':flag:': '🚩',
  ':trophy:': '🏆',
  ':medal:': '🏅',
  ':gem:': '💎',
  ':money:': '💰',
  ':briefcase:': '💼',
  ':hammer:': '🔨',
  ':wrench:': '🔧',
  ':gear:': '⚙️',
  ':lock:': '🔒',
  ':key:': '🔑',
  ':mag:': '🔍',
  ':eye:': '👁️',
  ':speech:': '💬',
  ':thought:': '💭',
  ':wave:': '👋',
  ':clap:': '👏',
  ':muscle:': '💪',
  ':pray:': '🙏',
  ':tada:': '🎉',
  ':party:': '🥳',
  ':coffee:': '☕',
  ':pizza:': '🍕',
  ':cake:': '🎂',
  ':sun:': '☀️',
  ':moon:': '🌙',
  ':cloud:': '☁️',
  ':rainbow:': '🌈',
  ':umbrella:': '☂️',
  ':snowflake:': '❄️',
  ':palm:': '🌴',
  ':tree:': '🌲',
  ':flower:': '🌸',
  ':cat:': '🐱',
  ':dog:': '🐕',
  ':bug:': '🐛',
  ':bee:': '🐝',
  ':butterfly:': '🦋',
  ':bird:': '🐦',
  ':fish:': '🐟',
  ':turtle:': '🐢',
  ':snake:': '🐍',
  ':dragon:': '🐉',
  ':unicorn:': '🦄',
  ':ghost:': '👻',
  ':alien:': '👽',
  ':robot:': '🤖',
  ':skull:': '💀',
  ':poop:': '💩',
  ':100:': '💯',
  ':1st:': '🥇',
  ':2nd:': '🥈',
  ':3rd:': '🥉',
  ':arrow_right:': '➡️',
  ':arrow_left:': '⬅️',
  ':arrow_up:': '⬆️',
  ':arrow_down:': '⬇️',
  ':play:': '▶️',
  ':pause:': '⏸️',
  ':stop:': '⏹️',
  ':record:': '⏺️',
  ':rewind:': '⏪',
  ':fast_forward:': '⏩',
  ':repeat:': '🔁',
  ':shuffle:': '🔀',
};

export const EMOJI_REGEX = new RegExp(
  Object.keys(EMOJI_MAP)
    .map((k) => k.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'))
    .join('|'),
  'g'
);

export function replaceEmojiShortcodes(text: string): string {
  return text.replace(EMOJI_REGEX, (match) => EMOJI_MAP[match] || match);
}
